package com.yadavarcheck.tisa.ui.theme

import androidx.compose.ui.graphics.Color

// Material 3 — Light
val Primary              = Color(0xFF1B6CA8)
val OnPrimary            = Color(0xFFFFFFFF)
val PrimaryContainer     = Color(0xFFD1E4FF)
val OnPrimaryContainer   = Color(0xFF001D36)
val Secondary            = Color(0xFF535F70)
val OnSecondary          = Color(0xFFFFFFFF)
val SecondaryContainer   = Color(0xFFD7E3F7)
val OnSecondaryContainer = Color(0xFF101C2B)
val Tertiary             = Color(0xFF6B5778)
val OnTertiary           = Color(0xFFFFFFFF)
val TertiaryContainer    = Color(0xFFF2DAFF)
val OnTertiaryContainer  = Color(0xFF251431)
val Error                = Color(0xFFBA1A1A)
val OnError              = Color(0xFFFFFFFF)
val ErrorContainer       = Color(0xFFFFDAD6)
val OnErrorContainer     = Color(0xFF410002)
val Background           = Color(0xFFFDFCFF)
val OnBackground         = Color(0xFF1A1C1E)
val Surface              = Color(0xFFFDFCFF)
val OnSurface            = Color(0xFF1A1C1E)
val SurfaceVariant       = Color(0xFFDFE2EB)
val OnSurfaceVariant     = Color(0xFF43474E)
val Outline              = Color(0xFF73777F)
val OutlineVariant       = Color(0xFFC3C7CF)

// Material 3 — Dark
val PrimaryDark              = Color(0xFF9ECAFF)
val OnPrimaryDark            = Color(0xFF003258)
val PrimaryContainerDark     = Color(0xFF00497D)
val OnPrimaryContainerDark   = Color(0xFFD1E4FF)
val BackgroundDark           = Color(0xFF1A1C1E)
val OnBackgroundDark         = Color(0xFFE2E2E6)
val SurfaceDark              = Color(0xFF1A1C1E)
val OnSurfaceDark            = Color(0xFFE2E2E6)
val SurfaceVariantDark       = Color(0xFF43474E)
val OnSurfaceVariantDark     = Color(0xFFC3C7CF)
val OutlineDark              = Color(0xFF8D9199)
val OutlineVariantDark       = Color(0xFF43474E)

// Status colors — used in CheckCard and StatusBadge
val StatusPending   = Color(0xFFF59E0B)
val StatusPaid      = Color(0xFF10B981)
val StatusDeposited = Color(0xFF3B82F6)
val StatusReturned  = Color(0xFFEF4444)
val StatusOverdue   = Color(0xFFDC2626)
val StatusCanceled  = Color(0xFF6B7280)
